version: "3"

services:
    myssh:
        restart: always
        image: myssh
        ports:
            - "0.0.0.0:22:22"
        volumes:
            - "/opt/myssh/log:/var/log"
    myssh2:
        restart: always
        image: myssh
        ports:
            - "0.0.0.0:2222:22"
        volumes:
            - "/opt/myssh/log:/var/log"
